version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: ci(Github Action)
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build(npm)
