name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: Features
    labels:
      - feature
      - enhancement
  - title: Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: Dependency Updates
    label: dependencies
  - title: Maintenance
    label: chore
  - title: Others
    labels:
      - ci
      - refactor
      - revert
      - style
  - title: Tests
    label: test
autolabeler:
  - label: breaking change
    title:
      - /(\(.+\))?!:/g
  - label: bug
    title:
      - /^fix(\(.+\))?!?:/g
  - label: build
    title:
      - /build(\(.+\))?!?:/g
  - label: chore
    title:
      - /^chore(\(.+\))?!?:/g
  - label: ci
    title:
      - /^ci(\(.+\))?!?:/g
  - label: documentation
    title:
      - /^docs(\(.+\))?!?:/g
  - label: enhancement
    title:
      - /^feat(\(.+\))?!?:/g
  - label: test
    title:
      - /^test(\(.+\))?!?:/g
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: \<*_&
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
exclude-contributors:
  - dependabot[bot]
template: |
  ## Changes

  $CHANGES
