name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: Features
    labels:
      - feature
      - enhancement
  - title: Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: Maintenance
    label: chore
autolabeler:
  - label: breaking change
    title:
      - /!(\(.+\))?:/g
  - label: bug
    title:
      - /^fix(\(.+\))?:/g
  - label: build
    title:
      - /build:/
  - label: chore
    title:
      - /^chore(\(.+\))?:/g
  - label: ci
    title:
      - /ci:/
  - label: documentation
    title:
      - /docs:/
  - label: enhancement
    title:
      - /^feat(\(.+\))?:/g
  - label: test
    title:
      - /^test(\(.+\))?:/
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: \<*_&
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
template: |
  ## Changes

  $CHANGES
