env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
overrides:
  - env:
      node: true
    files:
      - .eslintrc.{js,cjs}
      - jest.config.ts
    parserOptions:
      sourceType: script
parserOptions:
  ecmaVersion: latest
  project:
    - tsconfig.json
  sourceType: module
plugins:
  - simple-import-sort
  - sort-class-members
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-class-members/sort-class-members:
    - 2
    - order:
        - "[static-properties]"
        - "[static-methods"
        - "[properties]"
        - "[conventional-private-properties]"
        - constructor
        - "[methods]"
        - "[conventional-private-methods]"
      accessorPairPositioning: getThenSet
      groups:
        allMethods:
          - type: method
            sort: alphabetical
