name: Document
on:
  pull_request:
    paths:
      - .github/workflows/document.yml
      - mod.ts
      - bark_client.ts
      - bark_message_builder.ts
      - enums/**
      - errors/**
      - types/**
      - internal/**
      - tests/**
      - deno.json
  push:
    branches:
      - master
    paths:
      - .github/workflows/document.yml
      - mod.ts
      - bark_client.ts
      - bark_message_builder.ts
      - enums/**
      - errors/**
      - types/**
      - internal/**
      - tests/**
      - deno.json
permissions:
  contents: read
jobs:
  document:
    name: Validate API documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Lint docs
        run: deno doc --lint mod.ts
