name: Lint
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  check:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Check format
        run: deno task fmt:check
      - name: Check lint
        run: deno task lint
