name: Test
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/test.yml
      - src/**
      - package.json
      - pnpm-lock.yaml
      - test/**
  pull_request:
    paths:
      - .github/workflows/test.yml
      - package.json
      - pnpm-lock.yaml
      - src/**
      - test/**
jobs:
  jest:
    name: Jest
    permissions:
      checks: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 21
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm i
      - name: Run jest
        env:
          CI: true
        run: pnpm run test
      - name: Publish Test Report
        if: success() || failure()
        uses: phoenix-actions/test-reporting@v12
        with:
          name: Jest Tests in Node ${{ matrix.node-version }}
          path: coverage/junit.xml
          output-to: step-summary
          reporter: jest-junit
