name: Test
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/test.yml
      - deno.json
      - mod.ts
      - bark_client.ts
      - bark_message_builder.ts
      - enums/**
      - errors/**
      - types/**
      - internal/**
      - tests/**
  pull_request:
    paths:
      - .github/workflows/test.yml
      - deno.json
      - mod.ts
      - bark_client.ts
      - bark_message_builder.ts
      - enums/**
      - errors/**
      - types/**
      - internal/**
      - tests/**
jobs:
  deno-test:
    name: Deno Test
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Run unit test
        env:
          CI: true
        run: deno task test
      - name: Publish Test Report
        if: success() || failure()
        uses: phoenix-actions/test-reporting@v15
        with:
          name: Deno Tests
          path: test-result/junit.xml
          output-to: step-summary
          reporter: jest-junit
      - name: Generate lcov report
        if: success() || failure()
        run: deno task coverage
      - name: Upload coverage report
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-lcov
          path: test-result/lcov.info

